# Generated by Django 4.2.3 on 2023-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='total_tests',
            field=models.IntegerField(default=0),
        ),
    ]
