# Generated by Django 4.2.3 on 2023-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_section_total_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INACT', 'Inactive'), ('PRC', 'Process')], default='ACT', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INACT', 'Inactive'), ('PRC', 'Process')], default='ACT', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INACT', 'Inactive'), ('PRC', 'Process')], default='ACT', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INACT', 'Inactive'), ('PRC', 'Process')], default='ACT', max_length=255),
        ),
    ]
