# Generated by Django 4.2.3 on 2023-07-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_section_status_alter_subject_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('SN', 'Seen'), ('DN', 'Done')], default='ACT', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
