# Generated by Django 4.2.3 on 2023-07-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_advertising'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_testing',
            field=models.BooleanField(default=False),
        ),
    ]
