# Generated by Django 4.2.3 on 2023-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_subject_name_ru_subject_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='image',
            field=models.ImageField(default=str, upload_to='advertising_images/'),
            preserve_default=False,
        ),
    ]
