# Generated by Django 4.2.3 on 2023-07-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_advertising_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='lang',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
