# Generated by Django 4.2.3 on 2023-07-28 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_description_subject_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='correct_answer',
            new_name='correct_answer_ru',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='lang',
            new_name='correct_answer_uz',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='question',
            new_name='question_ru',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='variants',
            new_name='variants_ru',
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_uz',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='variants_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
    ]
