# Generated by Django 4.2.3 on 2023-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_description_section_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default=str, upload_to='test_images/'),
            preserve_default=False,
        ),
    ]
