# Generated by Django 4.2.3 on 2023-08-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
